export const uiCopy = {
  sidebar: {
    ariaLabel: '侧边栏',
    search: '搜索',
    home: '首页',
    newPage: '新建页面',
    pageTree: '页面树',
    expandPage: '展开页面',
    collapsePage: '收起页面',
  },
  search: {
    title: '全局搜索',
    placeholder: '搜索页面或内容',
    emptyQuery: '输入关键词搜索页面和内容',
    noResults: '没有找到匹配内容',
    openPage: '打开页面',
    close: '关闭搜索',
  },
  app: {
    loading: '正在加载...',
    bootstrapError: '数据加载失败，请关闭其他知栖窗口后重试。',
    pageNotFound: '页面不存在',
    renderError: '页面出了点问题，请返回侧边栏重新打开。',
  },
  page: {
    untitled: '未命名',
    addCover: '添加封面',
    changeCover: '更换封面',
    removeCover: '移除封面',
    addIcon: '添加图标',
    removeIcon: '移除图标',
    menu: '页面菜单',
    viewSection: '视图',
    smallText: '小字号正文',
    fontFamily: '页面字体',
    fontDefault: '默认',
    fontSerif: '衬线',
    fontMono: '等宽',
    outlineVisible: '显示页面目录',
    adaptiveWidth: '自适应正文宽度',
    typeSlash: '输入 / 打开命令菜单',
  },
  editor: {
    addBlock: '添加块',
    childPage: '子页面',
  },
  saveStatus: {
    idle: '未保存',
    saving: '保存中...',
    saved: '已保存',
    error: '保存失败',
  },
  export: {
    section: '备份与恢复',
    archive: '创建完整备份',
    importArchive: '从备份恢复',
    exportingArchive: '正在导出完整备份',
    importingArchive: '正在恢复完整备份',
    refreshingWorkspace: '正在刷新工作区',
    exportComplete: '完整备份已导出',
    importComplete: '备份恢复完成',
    exportError: '导出失败，请稍后重试。',
    importConfirm: '导入会覆盖当前本地内容，确认继续吗？',
    importError: '导入失败，请检查备份文件格式。',
  },
} as const
