export const uiCopy = {
  sidebar: {
    ariaLabel: '侧边栏',
    search: '搜索',
    newPage: '新建页面',
    import: '导入内容',
    notifications: '消息',
    more: '更多',
    tools: '侧边栏工具',
    localWorkspace: '本地工作区',
    desktopApp: '桌面端',
    compactMode: '紧凑模式',
    classicMode: '经典模式',
    systemSection: '系统',
    pageTree: '页面树',
    pinnedSection: '星标置顶',
    sharedSection: '共享页面',
    myPagesSection: '我的页面',
    pinToTop: '星标置顶',
    unpinFromTop: '取消置顶',
    expandPage: '展开页面',
    collapsePage: '收起页面',
    expandSection: '展开',
    collapseSection: '收起',
  },
  search: {
    title: '全局搜索',
    placeholder: '搜索页面或内容',
    emptyQuery: '输入关键词搜索页面和内容',
    noResults: '没有找到匹配内容',
    openPage: '打开页面',
    close: '关闭搜索',
    filters: {
      all: '全部',
      page: '页面',
      whiteboard: '白板',
      mindmap: '导图',
      dataTable: '数据表格',
      tags: '标签',
      status: '状态',
    },
    groups: {
      page: '页面',
      whiteboard: '白板',
      mindmap: '导图',
      dataTable: '数据表格',
    },
  },
  app: {
    loading: '正在加载...',
    bootstrapError: '数据加载失败，请关闭其他知栖窗口后重试。',
    pageNotFound: '页面不存在',
    renderError: '页面出了点问题，请返回侧边栏重新打开。',
  },
  clipboardCapture: {
    title: '剪贴板捕获',
    confirmAction: '收进收件箱',
    imageSummary: '检测到新的图片内容',
    richTextSummary: '检测到新的富文本内容',
    failureTitle: '收进收件箱失败',
    failureBody: '这次内容没有成功保存，请稍后重试。',
  },
  page: {
    untitled: '未命名',
    addCover: '添加封面',
    changeCover: '更换封面',
    removeCover: '移除封面',
    addIcon: '添加图标',
    removeIcon: '移除图标',
    menu: '页面菜单',
    viewSection: '视图',
    smallText: '小字号正文',
    fontFamily: '页面字体',
    fontDefault: '默认',
    fontSerif: '衬线',
    fontMono: '等宽',
    outlineVisible: '显示页面目录',
    propertiesVisible: '显示页面属性',
    adaptiveWidth: '自适应正文宽度',
    typeSlash: '输入 / 打开命令菜单',
  },
  pageProperties: {
    title: '页面属性',
    add: '添加属性',
    emptyValue: '空',
    editValue: '编辑属性',
    editMultiSelect: '编辑标签，使用逗号分隔',
    clearDate: '清空日期',
    today: '今天',
  },
  pageRelations: {
    title: '页面关系',
    backlinks: '链接到此页面',
    mentions: '提及此页面',
  },
  editor: {
    addBlock: '添加块',
    childPage: '子页面',
    pageRelation: {
      linkSuggestions: '页面链接建议',
      mentionSuggestions: '页面提及建议',
      createPage: (title: string) => `新建页面“${title}”`,
    },
  },
  saveStatus: {
    idle: '未保存',
    saving: '保存中...',
    saved: '已保存',
    error: '保存失败',
  },
  export: {
    workspace: '全部导出',
    exportingWorkspace: '正在导出全部内容',
    workspaceExportComplete: '全部内容已导出',
    importWorkspace: '导入完整备份',
    importMarkdown: '导入 Markdown',
    importingWorkspace: '正在导入完整备份',
    workspaceImportComplete: '完整备份已导入',
    section: '页面导入导出',
    archive: '导出当前页面',
    importArchive: '导入页面包',
    exportingArchive: '正在导出当前页面',
    preparingImport: '正在准备导入页面包',
    importingArchive: '正在导入页面包',
    refreshingWorkspace: '正在刷新工作区',
    exportComplete: '当前页面已导出',
    importComplete: '页面包导入完成',
    exportError: '导出失败，请稍后重试。',
    workspaceImportConfirm: '导入完整备份会覆盖当前工作区内容，建议先导出备份，确认继续吗？',
    workspaceImportError: '导入失败，请检查工作区备份格式。',
    workspaceImportWrongKind: '这是页面包，请使用“导入页面包”。',
    importConfirm: '导入会新增为一个顶层页面，确认继续吗？',
    importError: '导入失败，请检查页面包格式。',
    pageImportWrongKind: '这是工作区备份，请使用“导入完整备份”。',
    unsupportedArchiveVersion: '该归档来自更高版本的知栖，当前版本暂不支持。',
    archiveMissingAsset: '归档缺少关联文件，未导入任何内容。',
    archiveCorrupt: '归档文件已损坏或不是知栖归档。',
  },
} as const
