export const uiCopy = {
  sidebar: {
    ariaLabel: '侧边栏',
    search: '搜索',
    newPage: '新建页面',
    import: '导入',
    notifications: '消息',
    more: '更多',
    tools: '侧边栏工具',
    localWorkspace: '本地工作区',
    desktopApp: '桌面端',
    compactMode: '紧凑模式',
    classicMode: '经典模式',
    pageTree: '页面树',
    pinnedSection: '星标置顶',
    sharedSection: '共享页面',
    myPagesSection: '我的页面',
    pinToTop: '星标置顶',
    unpinFromTop: '取消置顶',
    expandPage: '展开页面',
    collapsePage: '收起页面',
    expandSection: '展开',
    collapseSection: '收起',
  },
  search: {
    title: '全局搜索',
    placeholder: '搜索页面或内容',
    emptyQuery: '输入关键词搜索页面和内容',
    noResults: '没有找到匹配内容',
    openPage: '打开页面',
    close: '关闭搜索',
  },
  app: {
    loading: '正在加载...',
    bootstrapError: '数据加载失败，请关闭其他知栖窗口后重试。',
    pageNotFound: '页面不存在',
    renderError: '页面出了点问题，请返回侧边栏重新打开。',
  },
  page: {
    untitled: '未命名',
    addCover: '添加封面',
    changeCover: '更换封面',
    removeCover: '移除封面',
    addIcon: '添加图标',
    removeIcon: '移除图标',
    menu: '页面菜单',
    viewSection: '视图',
    smallText: '小字号正文',
    fontFamily: '页面字体',
    fontDefault: '默认',
    fontSerif: '衬线',
    fontMono: '等宽',
    outlineVisible: '显示页面目录',
    adaptiveWidth: '自适应正文宽度',
    typeSlash: '输入 / 打开命令菜单',
  },
  editor: {
    addBlock: '添加块',
    childPage: '子页面',
  },
  saveStatus: {
    idle: '未保存',
    saving: '保存中...',
    saved: '已保存',
    error: '保存失败',
  },
  export: {
    workspace: '全部导出',
    exportingWorkspace: '正在导出全部内容',
    workspaceExportComplete: '全部内容已导出',
    section: '页面导入导出',
    archive: '导出当前页面',
    importArchive: '导入页面包',
    exportingArchive: '正在导出当前页面',
    preparingImport: '正在准备导入页面包',
    importingArchive: '正在导入页面包',
    refreshingWorkspace: '正在刷新工作区',
    exportComplete: '当前页面已导出',
    importComplete: '页面包导入完成',
    exportError: '导出失败，请稍后重试。',
    importConfirm: '导入会新增为一个顶层页面，确认继续吗？',
    importError: '导入失败，请检查页面包格式。',
  },
} as const
