import {
  createDefaultDatabaseView,
  createProperty,
  getDefaultViewName,
  getNextGeneratedViewName,
  isAutoGeneratedViewName,
  makeId,
  nowIso,
} from "./factory";
import type {
  AppState,
  BoardCardSortMode,
  DatabaseRecord,
  DatabaseView,
  FilterRule,
  Property,
  PropertyConfig,
  PropertyType,
  RecordValue,
  RecordPage,
  SelectOption,
  SortRule,
} from "./types";

type AddPropertyInput = {
  name: string;
  type: Exclude<PropertyType, "title"> | "title";
  insertPosition?: {
    relativeToPropertyId: string;
    side: "left" | "right";
  };
};

type MoveDirection = "left" | "right";

const DEFAULT_SELECT_OPTIONS: Array<Pick<SelectOption, "label" | "color">> = [
  { label: "待开始", color: "#64748b" },
  { label: "进行中", color: "#2563eb" },
  { label: "已完成", color: "#16a34a" },
];
const OPTION_COLOR_PLACEHOLDER = "#475569";
const OPTION_COLOR_PALETTE = [
  "#7c3aed",
  "#2563eb",
  "#0f766e",
  "#16a34a",
  "#ca8a04",
  "#ea580c",
  "#db2777",
  "#dc2626",
  "#475569",
];
const DEFAULT_BOARD_COLUMN_IDS = ["todo", "doing", "done", "ungrouped"];
const DEFAULT_TABLE_GROUP_IDS = ["ungrouped"];
const TABLE_PAGE_SIZE_OPTIONS = [10, 20, 30, 50];

function createDefaultOptions(): SelectOption[] {
  return DEFAULT_SELECT_OPTIONS.map((option) => ({
    id: makeId("option"),
    label: option.label,
    color: option.color,
  }));
}

function getNextOptionColor(usedColors: Set<string>, preferredIndex: number) {
  for (let offset = 0; offset < OPTION_COLOR_PALETTE.length; offset += 1) {
    const color =
      OPTION_COLOR_PALETTE[(preferredIndex + offset) % OPTION_COLOR_PALETTE.length];

    if (!usedColors.has(color)) {
      return color;
    }
  }

  return OPTION_COLOR_PALETTE[preferredIndex % OPTION_COLOR_PALETTE.length];
}

function normalizeSelectOptions(
  previousOptions: SelectOption[] | undefined,
  nextOptions: SelectOption[],
) {
  const previousById = new Map(previousOptions?.map((option) => [option.id, option]) ?? []);
  const previousByLabel = new Map(
    previousOptions?.map((option) => [option.label, option]) ?? [],
  );
  const usedColors = new Set<string>();

  return nextOptions.map((option, index) => {
    const previousOption =
      previousById.get(option.id) ?? previousByLabel.get(option.label);
    const explicitColor =
      option.color && option.color !== OPTION_COLOR_PLACEHOLDER
        ? option.color
        : null;
    const resolvedColor =
      explicitColor ??
      (previousOption?.color && previousOption.color !== OPTION_COLOR_PLACEHOLDER
        ? previousOption.color
        : !option.color || option.color === OPTION_COLOR_PLACEHOLDER
        ? getNextOptionColor(usedColors, index)
        : option.color);

    usedColors.add(resolvedColor);

    return {
      ...option,
      id: previousOption?.id ?? option.id,
      color: resolvedColor,
    };
  });
}

function areRecordValuesEqual(left: RecordValue, right: RecordValue) {
  if (Array.isArray(left) || Array.isArray(right)) {
    if (!Array.isArray(left) || !Array.isArray(right) || left.length !== right.length) {
      return false;
    }

    return left.every((value, index) => value === right[index]);
  }

  return left === right;
}

function syncOptionValue(
  propertyType: PropertyType,
  currentValue: RecordValue,
  previousOptions: SelectOption[] | undefined,
  nextOptions: SelectOption[],
): RecordValue {
  const nextOptionById = new Map(nextOptions.map((option) => [option.id, option]));
  const nextLabels = new Set(nextOptions.map((option) => option.label));
  const labelMap = new Map<string, string>();

  for (const previousOption of previousOptions ?? []) {
    const nextOption = nextOptionById.get(previousOption.id);

    if (nextOption) {
      labelMap.set(previousOption.label, nextOption.label);
    }
  }

  if (propertyType === "select") {
    if (typeof currentValue !== "string" || currentValue.length === 0) {
      return currentValue;
    }

    const mappedValue = labelMap.get(currentValue) ?? currentValue;
    return nextLabels.has(mappedValue) ? mappedValue : "";
  }

  if (propertyType === "multiSelect") {
    if (!Array.isArray(currentValue) || currentValue.length === 0) {
      return currentValue;
    }

    return currentValue.flatMap((label) => {
      const mappedValue = labelMap.get(label) ?? label;
      return nextLabels.has(mappedValue) ? [mappedValue] : [];
    });
  }

  return currentValue;
}

function getPropertyConfig(type: PropertyType): PropertyConfig {
  if (type === "select" || type === "multiSelect") {
    return { options: createDefaultOptions() };
  }

  if (type === "formula") {
    return { formulaExpression: "" };
  }

  return {};
}

function normalizePropertyConfig(
  type: PropertyType,
  config: PropertyConfig,
): PropertyConfig {
  if (type === "select" || type === "multiSelect") {
    return {
      ...config,
      options: normalizeSelectOptions(undefined, config.options ?? []),
    };
  }

  return config;
}

function patchProperty(
  property: Property,
  updates: Partial<Pick<Property, "name" | "type" | "config">>,
): Property {
  return {
    ...property,
    ...updates,
    updatedAt: nowIso(),
  };
}

function touchDatabase(
  state: AppState,
  propertyOrder = state.database.propertyOrder,
) {
  return {
    ...state.database,
    propertyOrder,
    updatedAt: nowIso(),
  };
}

function normalizePropertyKey(name: string) {
  const normalized = name
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "_")
    .replace(/[^a-z0-9_]/g, "")
    .replace(/^_+|_+$/g, "");

  return normalized || "field";
}

function makeUniquePropertyKey(baseKey: string, usedKeys: Set<string>) {
  if (!usedKeys.has(baseKey)) {
    usedKeys.add(baseKey);
    return baseKey;
  }

  let suffix = 2;
  let nextKey = `${baseKey}_${suffix}`;
  while (usedKeys.has(nextKey)) {
    suffix += 1;
    nextKey = `${baseKey}_${suffix}`;
  }

  usedKeys.add(nextKey);
  return nextKey;
}

function createUniquePropertyKey(state: AppState, name: string) {
  const baseKey = normalizePropertyKey(name);
  const existingKeys = new Set(
    Object.values(state.properties).map((property) => property.key),
  );

  return makeUniquePropertyKey(baseKey, existingKeys);
}

function isTitleProperty(property: Property | undefined) {
  return property?.type === "title";
}

function createNormalizedProperty(
  property: Property,
  type: PropertyType,
  key: string,
): Property {
  const hasChanged = property.type !== type || property.key !== key;

  return {
    ...property,
    type,
    key,
    config:
      property.type === type
        ? normalizePropertyConfig(type, property.config)
        : getPropertyConfig(type),
    updatedAt: hasChanged ? nowIso() : property.updatedAt,
  };
}

type LegacyDatabaseState = {
  sort?: SortRule | null;
  filters?: FilterRule[];
  view?: Partial<DatabaseView> & {
    ganttDatePropertyId?: string | null;
  };
};

function normalizeSortRule(
  sort: SortRule | null | undefined,
  properties: Record<string, Property>,
) {
  if (!sort?.propertyId || !properties[sort.propertyId]) {
    return null;
  }

  return {
    propertyId: sort.propertyId,
    direction: sort.direction === "desc" ? "desc" : "asc",
  } satisfies SortRule;
}

function normalizeFilterRules(
  filters: FilterRule[] | undefined,
  properties: Record<string, Property>,
) {
  return (filters ?? []).filter(
    (filter) =>
      Boolean(filter?.id) &&
      Boolean(filter?.propertyId) &&
      Boolean(properties[filter.propertyId]),
  );
}

function normalizeBoardColumnOrder(
  boardGroupPropertyId: string | null,
  boardColumnOrder: string[] | undefined,
  properties: Record<string, Property>,
) {
  if (!boardGroupPropertyId) {
    return [];
  }

  const property = properties[boardGroupPropertyId];

  if (
    !property ||
    (property.type !== "select" && property.type !== "multiSelect") ||
    !property.config.options?.length
  ) {
    return [];
  }

  const optionIds = property.config.options.map((option) => option.id);
  const validOptionIds = new Set(optionIds);
  const seenIds = new Set<string>();
  const normalizedOrder = (boardColumnOrder ?? []).filter((optionId) => {
    if (!validOptionIds.has(optionId) || seenIds.has(optionId)) {
      return false;
    }

    seenIds.add(optionId);
    return true;
  });

  for (const optionId of optionIds) {
    if (!seenIds.has(optionId)) {
      normalizedOrder.push(optionId);
    }
  }

  return normalizedOrder;
}

function normalizeTableGroupOrder(
  tableGroupPropertyId: string | null,
  tableGroupOrder: string[] | undefined,
  properties: Record<string, Property>,
) {
  if (!tableGroupPropertyId) {
    return [];
  }

  const property = properties[tableGroupPropertyId];

  if (
    !property ||
    (property.type !== "select" && property.type !== "multiSelect") ||
    !property.config.options?.length
  ) {
    return Array.from(new Set(tableGroupOrder ?? []));
  }

  const optionIds = property.config.options.map((option) => option.id);
  const validOptionIds = new Set(optionIds);
  const seenIds = new Set<string>();
  const normalizedOrder = (tableGroupOrder ?? []).filter((optionId) => {
    if (!validOptionIds.has(optionId) || seenIds.has(optionId)) {
      return false;
    }

    seenIds.add(optionId);
    return true;
  });

  for (const optionId of optionIds) {
    if (!seenIds.has(optionId)) {
      normalizedOrder.push(optionId);
    }
  }

  return normalizedOrder;
}

function normalizeBoardHiddenColumnIds(
  boardGroupPropertyId: string | null,
  boardHiddenColumnIds: string[] | undefined,
  properties: Record<string, Property>,
) {
  const validColumnIds = new Set<string>(DEFAULT_BOARD_COLUMN_IDS);

  if (boardGroupPropertyId) {
    const property = properties[boardGroupPropertyId];

    if (
      property &&
      (property.type === "select" || property.type === "multiSelect")
    ) {
      for (const option of property.config.options ?? []) {
        validColumnIds.add(option.id);
      }
    }
  }

  return Array.from(
    new Set(
      (boardHiddenColumnIds ?? []).filter((columnId) =>
        validColumnIds.has(columnId),
      ),
    ),
  );
}

function normalizeTableHiddenGroupIds(
  tableGroupPropertyId: string | null,
  tableHiddenGroupIds: string[] | undefined,
  properties: Record<string, Property>,
) {
  if (!tableGroupPropertyId) {
    return [];
  }

  const property = properties[tableGroupPropertyId];

  if (
    property &&
    (property.type === "select" || property.type === "multiSelect")
  ) {
    const validGroupIds = new Set<string>(DEFAULT_TABLE_GROUP_IDS);

    for (const option of property.config.options ?? []) {
      validGroupIds.add(option.id);
    }

    return Array.from(
      new Set(
        (tableHiddenGroupIds ?? []).filter((groupId) => validGroupIds.has(groupId)),
      ),
    );
  }

  return Array.from(new Set(tableHiddenGroupIds ?? []));
}

function normalizeTableCollapsedGroupIds(
  tableGroupPropertyId: string | null,
  tableCollapsedGroupIds: string[] | undefined,
  properties: Record<string, Property>,
) {
  if (!tableGroupPropertyId) {
    return [];
  }

  const property = properties[tableGroupPropertyId];

  if (
    property &&
    (property.type === "select" || property.type === "multiSelect")
  ) {
    const validGroupIds = new Set<string>(DEFAULT_TABLE_GROUP_IDS);

    for (const option of property.config.options ?? []) {
      validGroupIds.add(option.id);
    }

    return Array.from(
      new Set(
        (tableCollapsedGroupIds ?? []).filter((groupId) =>
          validGroupIds.has(groupId),
        ),
      ),
    );
  }

  return Array.from(new Set(tableCollapsedGroupIds ?? []));
}

function normalizeBoardCardSortMode(
  boardCardSortMode: BoardCardSortMode | undefined,
): BoardCardSortMode {
  if (
    boardCardSortMode === "titleAsc" ||
    boardCardSortMode === "titleDesc"
  ) {
    return boardCardSortMode;
  }

  return "manual";
}

function normalizeTablePageSize(tablePageSize: number | undefined) {
  return TABLE_PAGE_SIZE_OPTIONS.includes(tablePageSize ?? 0)
    ? tablePageSize!
    : 10;
}

function normalizeDatabaseView(
  view:
    | (Partial<DatabaseView> & {
        ganttDatePropertyId?: string | null;
      })
    | undefined,
  properties: Record<string, Property>,
): DatabaseView {
  const fallback = createDefaultDatabaseView();
  const normalizedLayout =
    view?.layout === "board" ||
    view?.layout === "gantt" ||
    view?.layout === "calendar"
      ? view.layout
      : fallback.layout;
  const validPropertyIds = new Set(Object.keys(properties));
  const canUseAsBoardGroup = (propertyId: string | null | undefined) => {
    if (!propertyId || !validPropertyIds.has(propertyId)) {
      return false;
    }

    const property = properties[propertyId];

    return (
      property?.type === "text" ||
      property?.type === "select" ||
      property?.type === "multiSelect"
    );
  };
  const canUseAsTableGroup = (propertyId: string | null | undefined) => {
    if (!propertyId || !validPropertyIds.has(propertyId)) {
      return false;
    }

    const property = properties[propertyId];

    return (
      property?.type === "text" ||
      property?.type === "number" ||
      property?.type === "select" ||
      property?.type === "multiSelect" ||
      property?.type === "date" ||
      property?.type === "checkbox"
    );
  };
  const canUseAsGanttDate = (propertyId: string | null | undefined) => {
    if (!propertyId || !validPropertyIds.has(propertyId)) {
      return false;
    }

    return properties[propertyId]?.type === "date";
  };
  const legacyGanttDatePropertyId = canUseAsGanttDate(view?.ganttDatePropertyId)
    ? view?.ganttDatePropertyId ?? null
    : null;
  const normalizedTableGroupPropertyId = canUseAsTableGroup(view?.tableGroupPropertyId)
    ? view?.tableGroupPropertyId ?? null
    : null;
  const normalizedBoardGroupPropertyId = canUseAsBoardGroup(view?.boardGroupPropertyId)
    ? view?.boardGroupPropertyId ?? null
    : null;
  const hiddenPropertyIds = (view?.hiddenPropertyIds ?? []).filter((propertyId) => {
    const property = properties[propertyId];

    return validPropertyIds.has(propertyId) && property?.type !== "title";
  });
  const columnWidths = Object.fromEntries(
    Object.entries(view?.columnWidths ?? {}).filter(
      ([propertyId, width]) =>
        validPropertyIds.has(propertyId) &&
        typeof width === "number" &&
        Number.isFinite(width) &&
        width > 0,
    ),
  );

  return {
    id: view?.id ?? fallback.id,
    name: view?.name?.trim() ? view.name.trim() : getDefaultViewName(normalizedLayout),
    layout: normalizedLayout,
    sort: normalizeSortRule(view?.sort, properties),
    filters: normalizeFilterRules(view?.filters, properties),
    tableGroupPropertyId: normalizedTableGroupPropertyId,
    tableGroupOrder: normalizeTableGroupOrder(
      normalizedTableGroupPropertyId,
      view?.tableGroupOrder,
      properties,
    ),
    tableHiddenGroupIds: normalizeTableHiddenGroupIds(
      normalizedTableGroupPropertyId,
      view?.tableHiddenGroupIds,
      properties,
    ),
    tableCollapsedGroupIds: normalizeTableCollapsedGroupIds(
      normalizedTableGroupPropertyId,
      view?.tableCollapsedGroupIds,
      properties,
    ),
    tableHideEmptyGroups:
      view?.tableHideEmptyGroups ?? fallback.tableHideEmptyGroups,
    boardGroupPropertyId: normalizedBoardGroupPropertyId,
    boardColumnOrder: normalizeBoardColumnOrder(
      normalizedBoardGroupPropertyId,
      view?.boardColumnOrder,
      properties,
    ),
    boardHiddenColumnIds: normalizeBoardHiddenColumnIds(
      normalizedBoardGroupPropertyId,
      view?.boardHiddenColumnIds,
      properties,
    ),
    boardRecordOrder: Array.from(new Set(view?.boardRecordOrder ?? [])),
    boardCardSortMode: normalizeBoardCardSortMode(view?.boardCardSortMode),
    boardShowPropertyNames:
      view?.boardShowPropertyNames ?? fallback.boardShowPropertyNames,
    ganttStartPropertyId: canUseAsGanttDate(view?.ganttStartPropertyId)
      ? view?.ganttStartPropertyId ?? null
      : legacyGanttDatePropertyId,
    ganttEndPropertyId: canUseAsGanttDate(view?.ganttEndPropertyId)
      ? view?.ganttEndPropertyId ?? null
      : null,
    ganttTimelineScale:
      view?.ganttTimelineScale === "week" || view?.ganttTimelineScale === "month"
        ? view.ganttTimelineScale
        : "day",
    calendarDatePropertyId: canUseAsGanttDate(view?.calendarDatePropertyId)
      ? view?.calendarDatePropertyId ?? null
      : null,
    openMode:
      view?.openMode === "centerPeek" || view?.openMode === "fullPage"
        ? view.openMode
        : fallback.openMode,
    tableWidthMode:
      view?.tableWidthMode === "content" ? "content" : fallback.tableWidthMode,
    tablePageSize: normalizeTablePageSize(view?.tablePageSize),
    wrapCells: view?.wrapCells ?? fallback.wrapCells,
    freezeFirstColumn: view?.freezeFirstColumn ?? fallback.freezeFirstColumn,
    hiddenPropertyIds,
    columnWidths,
    createdAt: view?.createdAt ?? fallback.createdAt,
    updatedAt: view?.updatedAt ?? fallback.updatedAt,
  };
}

function normalizeDatabaseViews(
  database: AppState["database"] & LegacyDatabaseState,
  properties: Record<string, Property>,
) {
  const viewsSource =
    database.views && Object.keys(database.views).length > 0
      ? database.views
      : null;

  if (!viewsSource) {
    const legacyView = normalizeDatabaseView(
      {
        ...database.view,
        sort: database.sort,
        filters: database.filters,
      },
      properties,
    );
    const normalizedLegacyView = isAutoGeneratedViewName(legacyView.name)
      ? {
          ...legacyView,
          name: getDefaultViewName(legacyView.layout),
        }
      : legacyView;

    return {
      activeViewId: normalizedLegacyView.id,
      viewOrder: [normalizedLegacyView.id],
      views: {
        [normalizedLegacyView.id]: normalizedLegacyView,
      },
    };
  }

  const seenIds = new Set<string>();
  const viewOrder = [...(database.viewOrder ?? []), ...Object.keys(viewsSource)].filter(
    (viewId) => {
      if (!viewsSource[viewId] || seenIds.has(viewId)) {
        return false;
      }

      seenIds.add(viewId);
      return true;
    },
  );

  const normalizedViews = Object.fromEntries(
    viewOrder.map((viewId) => [
      viewId,
      normalizeDatabaseView(
        {
          ...viewsSource[viewId],
          id: viewId,
        },
        properties,
      ),
    ]),
  );
  const assignedViewNames = new Set<string>();
  const renamedViews = Object.fromEntries(
    viewOrder.map((viewId) => {
      const currentView = normalizedViews[viewId];

      if (!isAutoGeneratedViewName(currentView.name)) {
        assignedViewNames.add(currentView.name);
        return [viewId, currentView];
      }

      const nextName = getNextGeneratedViewName(assignedViewNames, currentView.layout);
      assignedViewNames.add(nextName);

      return [
        viewId,
        nextName === currentView.name
          ? currentView
          : {
              ...currentView,
              name: nextName,
            },
      ];
    }),
  );

  const firstViewId = viewOrder[0] ?? createDefaultDatabaseView().id;

  return {
    activeViewId:
      database.activeViewId && renamedViews[database.activeViewId]
        ? database.activeViewId
        : firstViewId,
    viewOrder,
    views: renamedViews,
  };
}

export function normalizeAppStateSchema(state: AppState): AppState {
  const orderedIds: string[] = [];
  const seenIds = new Set<string>();

  for (const propertyId of state.database.propertyOrder) {
    if (!state.properties[propertyId] || seenIds.has(propertyId)) {
      continue;
    }

    orderedIds.push(propertyId);
    seenIds.add(propertyId);
  }

  for (const propertyId of Object.keys(state.properties)) {
    if (seenIds.has(propertyId)) {
      continue;
    }

    orderedIds.push(propertyId);
    seenIds.add(propertyId);
  }

  const nextProperties = { ...state.properties };
  const nextPropertyOrder = [...orderedIds];

  if (nextPropertyOrder.length === 0) {
    const titleProperty = createProperty({
      key: "name",
      name: "名称",
      type: "title",
    });
    nextProperties[titleProperty.id] = titleProperty;
    nextPropertyOrder.push(titleProperty.id);
  }

  const canonicalTitleId =
    nextPropertyOrder.find((propertyId) =>
      isTitleProperty(nextProperties[propertyId]),
    ) ?? nextPropertyOrder[0];
  const normalizedPropertyOrder = [
    canonicalTitleId,
    ...nextPropertyOrder.filter((propertyId) => propertyId !== canonicalTitleId),
  ];
  const usedKeys = new Set<string>();

  const normalizedProperties = Object.fromEntries(
    normalizedPropertyOrder.map((propertyId) => {
      const property = nextProperties[propertyId];
      const nextType =
        propertyId === canonicalTitleId
          ? "title"
          : property.type === "title"
            ? "text"
            : property.type;
      const nextKey = makeUniquePropertyKey(
        normalizePropertyKey(property.key || property.name),
        usedKeys,
      );

      return [
        propertyId,
        createNormalizedProperty(property, nextType, nextKey),
      ];
    }),
  );
  const normalizedViews = normalizeDatabaseViews(
    state.database as AppState["database"] & LegacyDatabaseState,
    normalizedProperties,
  );

  return {
    ...state,
    database: {
      ...state.database,
      propertyOrder: normalizedPropertyOrder,
      ...normalizedViews,
    },
    properties: normalizedProperties,
  };
}

export function createRecord(
  state: AppState,
  initialValues: Record<string, RecordValue> = {},
): AppState {
  const timestamp = nowIso();
  const recordId = makeId("record");
  const record: DatabaseRecord = {
    id: recordId,
    title: "",
    values: { ...initialValues },
    createdAt: timestamp,
    updatedAt: timestamp,
  };
  const recordPage: RecordPage = {
    recordId,
    blockIds: [],
    updatedAt: timestamp,
  };

  return {
    ...state,
    records: {
      ...state.records,
      [recordId]: record,
    },
    recordPages: {
      ...state.recordPages,
      [recordId]: recordPage,
    },
  };
}

export function deleteRecord(state: AppState, recordId: string): AppState {
  const nextRecords = { ...state.records };
  const nextRecordPages = { ...state.recordPages };
  const nextBlocks = { ...state.blocks };
  const nextAssets = { ...state.assets };
  const blockIds = state.recordPages[recordId]?.blockIds ?? [];

  for (const blockId of blockIds) {
    const block = nextBlocks[blockId];
    if (!block) {
      continue;
    }

    if (block.imageAssetId) {
      delete nextAssets[block.imageAssetId];
    }

    delete nextBlocks[blockId];
  }

  delete nextRecords[recordId];
  delete nextRecordPages[recordId];

  return {
    ...state,
    assets: nextAssets,
    blocks: nextBlocks,
    records: nextRecords,
    recordPages: nextRecordPages,
  };
}

export function addProperty(state: AppState, input: AddPropertyInput): AppState {
  if (input.type === "title") {
    return state;
  }

  const property = createProperty({
    key: createUniquePropertyKey(state, input.name),
    name: input.name,
    type: input.type,
  });
  const nextProperty = patchProperty(property, {
    config: getPropertyConfig(input.type),
  });
  const nextPropertyOrder = [...state.database.propertyOrder];
  const relativeToPropertyId = input.insertPosition?.relativeToPropertyId;
  const relativeIndex =
    relativeToPropertyId == null ? -1 : nextPropertyOrder.indexOf(relativeToPropertyId);

  if (relativeIndex === -1) {
    nextPropertyOrder.push(nextProperty.id);
  } else {
    const nextIndex =
      input.insertPosition?.side === "left" ? relativeIndex : relativeIndex + 1;
    const insertIndex = Math.min(
      Math.max(nextIndex, 1),
      nextPropertyOrder.length,
    );

    nextPropertyOrder.splice(insertIndex, 0, nextProperty.id);
  }

  return {
    ...state,
    database: touchDatabase(state, nextPropertyOrder),
    properties: {
      ...state.properties,
      [nextProperty.id]: nextProperty,
    },
  };
}

export function renameProperty(
  state: AppState,
  propertyId: string,
  name: string,
): AppState {
  const property = state.properties[propertyId];
  if (!property) {
    return state;
  }

  return {
    ...state,
    properties: {
      ...state.properties,
      [propertyId]: patchProperty(property, { name }),
    },
  };
}

export function updatePropertyType(
  state: AppState,
  propertyId: string,
  type: PropertyType,
): AppState {
  const property = state.properties[propertyId];
  if (!property) {
    return state;
  }

  if (isTitleProperty(property) || type === "title" || property.type === type) {
    return state;
  }

  return {
    ...state,
    properties: {
      ...state.properties,
      [propertyId]: patchProperty(property, {
        type,
        config: getPropertyConfig(type),
      }),
    },
  };
}

export function moveProperty(
  state: AppState,
  propertyId: string,
  direction: MoveDirection,
): AppState {
  const property = state.properties[propertyId];
  const currentIndex = state.database.propertyOrder.indexOf(propertyId);
  if (!property || currentIndex === -1 || isTitleProperty(property)) {
    return state;
  }

  const targetIndex = direction === "left" ? currentIndex - 1 : currentIndex + 1;
  if (targetIndex <= 0 || targetIndex >= state.database.propertyOrder.length) {
    return state;
  }

  const nextPropertyOrder = [...state.database.propertyOrder];
  [nextPropertyOrder[currentIndex], nextPropertyOrder[targetIndex]] = [
    nextPropertyOrder[targetIndex],
    nextPropertyOrder[currentIndex],
  ];

  return {
    ...state,
    database: touchDatabase(state, nextPropertyOrder),
  };
}

export function deleteProperty(state: AppState, propertyId: string): AppState {
  const property = state.properties[propertyId];
  if (!property || isTitleProperty(property)) {
    return state;
  }

  const nextProperties = { ...state.properties };
  delete nextProperties[propertyId];

  const nextPropertyOrder = state.database.propertyOrder.filter(
    (id) => id !== propertyId,
  );
  const nextRecords = Object.fromEntries(
    Object.entries(state.records).map(([recordId, record]) => {
      const nextValues = { ...record.values };
      delete nextValues[propertyId];

      return [
        recordId,
        {
          ...record,
          values: nextValues,
        },
      ];
    }),
  );

  return {
    ...state,
    database: touchDatabase(state, nextPropertyOrder),
    properties: nextProperties,
    records: nextRecords,
  };
}

export function updatePropertyOptions(
  state: AppState,
  propertyId: string,
  options: SelectOption[],
): AppState {
  const property = state.properties[propertyId];
  if (!property) {
    return state;
  }

  const nextOptions = normalizeSelectOptions(property.config.options, options);
  const nextRecords = Object.fromEntries(
    Object.entries(state.records).map(([recordId, record]) => {
      const currentValue = record.values[propertyId];
      if (currentValue === undefined) {
        return [recordId, record];
      }

      const nextValue = syncOptionValue(
        property.type,
        currentValue,
        property.config.options,
        nextOptions,
      );

      if (areRecordValuesEqual(currentValue, nextValue)) {
        return [recordId, record];
      }

      return [
        recordId,
        {
          ...record,
          values: {
            ...record.values,
            [propertyId]: nextValue,
          },
          updatedAt: nowIso(),
        },
      ];
    }),
  );

  return {
    ...state,
    properties: {
      ...state.properties,
      [propertyId]: patchProperty(property, {
        config: {
          ...property.config,
          options: nextOptions,
        },
      }),
    },
    records: nextRecords,
  };
}

export function updateFormulaExpression(
  state: AppState,
  propertyId: string,
  formulaExpression: string,
): AppState {
  const property = state.properties[propertyId];
  if (!property) {
    return state;
  }

  return {
    ...state,
    properties: {
      ...state.properties,
      [propertyId]: patchProperty(property, {
        config: {
          ...property.config,
          formulaExpression,
        },
      }),
    },
  };
}

export function normalizeValueForProperty(
  property: Property,
  rawValue: string | boolean | string[],
): RecordValue {
  switch (property.type) {
    case "title":
    case "text":
    case "date":
      return String(rawValue);
    case "number":
      return rawValue === "" ? null : Number(rawValue);
    case "checkbox":
      return Boolean(rawValue);
    case "multiSelect":
      return Array.isArray(rawValue) ? rawValue : [];
    default:
      return Array.isArray(rawValue) ? (rawValue[0] ?? "") : String(rawValue);
  }
}

export function updateRecordValue(
  state: AppState,
  recordId: string,
  property: Property,
  rawValue: string | boolean | string[],
): AppState {
  const record = state.records[recordId];
  if (!record) {
    return state;
  }

  const nextValue = normalizeValueForProperty(property, rawValue);
  const nextRecord =
    property.type === "title"
      ? {
          ...record,
          title: nextValue == null ? "" : String(nextValue),
          updatedAt: nowIso(),
        }
      : {
          ...record,
          values: {
            ...record.values,
            [property.id]: nextValue,
          },
          updatedAt: nowIso(),
        };

  return {
    ...state,
    records: {
      ...state.records,
      [recordId]: nextRecord,
    },
  };
}
