import type {
  AppState,
  Database,
  DatabaseView,
  Property,
  PropertyType,
} from "./types";

type CreatePropertyInput = {
  key: string;
  name: string;
  type: PropertyType;
};

export function makeId(prefix: string) {
  return `${prefix}_${crypto.randomUUID()}`;
}

export function nowIso() {
  return new Date().toISOString();
}

export function createProperty(input: CreatePropertyInput): Property {
  const timestamp = nowIso();

  return {
    id: makeId("property"),
    key: input.key,
    name: input.name,
    type: input.type,
    config: {},
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

const DEFAULT_VIEW_NAMES: Record<DatabaseView["layout"], string> = {
  table: "\u8868\u683c\u89c6\u56fe",
  board: "\u770b\u677f\u89c6\u56fe",
  gantt: "\u7518\u7279\u56fe\u89c6\u56fe",
  calendar: "\u65e5\u5386\u89c6\u56fe",
};

const LEGACY_AUTO_VIEW_NAME_PATTERN = /^\u89c6\u56fe \d+$/;

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function getDefaultViewName(layout: DatabaseView["layout"] = "table") {
  return DEFAULT_VIEW_NAMES[layout];
}

export function isAutoGeneratedViewName(name: string) {
  const normalizedName = name.trim();

  if (normalizedName === "\u5168\u90e8\u6761\u76ee" || LEGACY_AUTO_VIEW_NAME_PATTERN.test(normalizedName)) {
    return true;
  }

  return Object.values(DEFAULT_VIEW_NAMES).some((defaultName) => {
    const pattern = new RegExp(`^${escapeRegExp(defaultName)}(?:\\d+)?$`);
    return pattern.test(normalizedName);
  });
}

export function getNextGeneratedViewName(
  existingNames: Iterable<string>,
  layout: DatabaseView["layout"],
) {
  const defaultName = getDefaultViewName(layout);
  const nameSet = new Set(Array.from(existingNames, (name) => name.trim()));

  if (!nameSet.has(defaultName)) {
    return defaultName;
  }

  let index = 2;
  let nextName = `${defaultName}${index}`;

  while (nameSet.has(nextName)) {
    index += 1;
    nextName = `${defaultName}${index}`;
  }

  return nextName;
}

export function createDefaultDatabaseView(
  layout: DatabaseView["layout"] = "table",
): DatabaseView {
  const timestamp = nowIso();

  return {
    id: makeId("view"),
    name: getDefaultViewName(layout),
    layout,
    sort: null,
    filters: [],
    tableGroupPropertyId: null,
    tableGroupOrder: [],
    tableHiddenGroupIds: [],
    tableCollapsedGroupIds: [],
    tableHideEmptyGroups: false,
    boardGroupPropertyId: null,
    boardColumnOrder: [],
    boardHiddenColumnIds: [],
    boardRecordOrder: [],
    boardCardSortMode: "manual",
    boardShowPropertyNames: true,
    ganttStartPropertyId: null,
    ganttEndPropertyId: null,
    calendarDatePropertyId: null,
    openMode: "sidePeek",
    tableWidthMode: "fitPage",
    wrapCells: false,
    freezeFirstColumn: false,
    hiddenPropertyIds: [],
    columnWidths: {},
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

export function createDatabase(propertyOrder: string[]): Database {
  const timestamp = nowIso();
  const defaultView = createDefaultDatabaseView();

  return {
    id: makeId("database"),
    name: "项目数据库",
    propertyOrder,
    activeViewId: defaultView.id,
    viewOrder: [defaultView.id],
    views: {
      [defaultView.id]: defaultView,
    },
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

export function createDefaultAppState(): AppState {
  const titleProperty = createProperty({
    key: "name",
    name: "名称",
    type: "title",
  });

  return {
    version: 1,
    database: createDatabase([titleProperty.id]),
    properties: {
      [titleProperty.id]: titleProperty,
    },
    records: {},
    recordPages: {},
    blocks: {},
    assets: {},
  };
}
