import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import {
  createDefaultAppState,
  createDefaultDatabaseView,
  getNextGeneratedViewName,
  isAutoGeneratedViewName,
  makeId,
  nowIso,
} from "../domain/factory";
import {
  addBlockAfter,
  attachImageAsset,
  deleteBlock,
  moveBlock,
  updateBlockChecked,
  updateBlockContent,
  updateBlockType,
} from "../domain/blocks";
import {
  addProperty,
  createRecord,
  deleteProperty,
  deleteRecord,
  moveProperty,
  normalizeAppStateSchema,
  renameProperty,
  updateFormulaExpression,
  updatePropertyOptions,
  updateRecordValue,
  updatePropertyType,
} from "../domain/database";
import type {
  AppState,
  Asset,
  Block,
  BlockType,
  DatabaseView,
  FilterRule,
  Property,
  PropertyType,
  RecordValue,
  SelectOption,
  SortRule,
} from "../domain/types";
import { loadAppState, saveAppState } from "../storage/appStateRepo";

export type SaveStatus = "idle" | "saving" | "saved" | "failed";

type AppStoreActions = {
  replaceState: (nextState: AppState) => void;
  createRecord: (initialValues?: Record<string, RecordValue>) => void;
  deleteRecord: (recordId: string) => void;
  setActiveView: (viewId: string) => void;
  createView: (layout?: DatabaseView["layout"]) => void;
  renameView: (viewId: string, name: string) => void;
  moveView: (
    viewId: string,
    targetViewId: string,
    placement?: "before" | "after",
  ) => void;
  duplicateView: (viewId: string) => void;
  deleteView: (viewId: string) => void;
  addProperty: (
    name: string,
    type: Exclude<PropertyType, "title">,
    insertPosition?: {
      relativeToPropertyId: string;
      side: "left" | "right";
    },
  ) => void;
  renameProperty: (propertyId: string, name: string) => void;
  updatePropertyType: (propertyId: string, type: PropertyType) => void;
  moveProperty: (propertyId: string, direction: "left" | "right") => void;
  deleteProperty: (propertyId: string) => void;
  updateRecordValue: (
    recordId: string,
    property: Property,
    value: string | boolean | string[],
  ) => void;
  updatePropertyOptions: (propertyId: string, options: SelectOption[]) => void;
  updateFormulaExpression: (
    propertyId: string,
    formulaExpression: string,
  ) => void;
  updateActiveView: (updates: Partial<DatabaseView>) => void;
  setActiveViewSort: (sort: SortRule | null) => void;
  setActiveViewFilters: (filters: FilterRule[]) => void;
  addBlock: (
    recordId: string,
    afterBlockId: string | null,
    type: BlockType,
  ) => string | null;
  updateBlockContent: (blockId: string, content: string) => void;
  patchBlock: (blockId: string, patch: Partial<Block>) => void;
  updateBlockType: (blockId: string, type: BlockType) => void;
  updateBlockChecked: (blockId: string, checked: boolean) => void;
  deleteBlock: (blockId: string) => void;
  moveBlock: (blockId: string, direction: "up" | "down") => void;
  attachImageAsset: (blockId: string, asset: Asset) => void;
};

type AppStoreContextValue = {
  state: AppState;
  loaded: boolean;
  saveStatus: SaveStatus;
  replaceState: (nextState: AppState) => void;
  actions: AppStoreActions;
};

interface AppStoreProviderProps {
  children: ReactNode;
  initialState?: AppState;
  onChange?: (nextState: AppState) => void;
  saveStatus?: SaveStatus;
}

const AppStoreContext = createContext<AppStoreContextValue | null>(null);

function getNextViewName(
  views: Record<string, DatabaseView>,
  layout: DatabaseView["layout"],
) {
  return getNextGeneratedViewName(
    Object.values(views).map((view) => view.name),
    layout,
  );
}

function getDuplicateViewName(views: Record<string, DatabaseView>, baseName: string) {
  const existingNames = new Set(Object.values(views).map((view) => view.name));
  const initialName = `${baseName} 副本`;

  if (!existingNames.has(initialName)) {
    return initialName;
  }

  let index = 2;
  let nextName = `${initialName} ${index}`;

  while (existingNames.has(nextName)) {
    index += 1;
    nextName = `${initialName} ${index}`;
  }

  return nextName;
}

function updateViewInState(
  currentState: AppState,
  viewId: string,
  updates: Partial<DatabaseView>,
) {
  const currentView = currentState.database.views[viewId];
  if (!currentView) {
    return currentState;
  }

  return {
    ...currentState,
    database: {
      ...currentState.database,
      updatedAt: nowIso(),
      views: {
        ...currentState.database.views,
        [viewId]: {
          ...currentView,
          ...updates,
          updatedAt: nowIso(),
        },
      },
    },
  };
}

function getAutoRenamedViewName(
  views: Record<string, DatabaseView>,
  currentView: DatabaseView,
  nextLayout: DatabaseView["layout"],
) {
  if (!isAutoGeneratedViewName(currentView.name)) {
    return currentView.name;
  }

  const otherViewNames = Object.values(views)
    .filter((view) => view.id !== currentView.id)
    .map((view) => view.name);

  return getNextGeneratedViewName(otherViewNames, nextLayout);
}

export function AppStoreProvider({
  children,
  initialState,
  onChange,
  saveStatus: controlledSaveStatus,
}: AppStoreProviderProps) {
  const isControlled = initialState !== undefined;
  const [state, setState] = useState<AppState>(() =>
    normalizeAppStateSchema(initialState ?? createDefaultAppState()),
  );
  const [loaded, setLoaded] = useState(isControlled);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>(isControlled ? "saved" : "idle");
  const saveTimerRef = useRef<number | null>(null);
  const hasFinishedInitialLoadRef = useRef(false);
  const saveRequestIdRef = useRef(0);

  useEffect(() => {
    if (isControlled) {
      setLoaded(true);
      return;
    }

    let cancelled = false;

    loadAppState()
      .then((storedState) => {
        if (cancelled) {
          return;
        }

        if (storedState) {
          setState(normalizeAppStateSchema(storedState));
        }
      })
      .catch(() => {
        if (!cancelled) {
          setSaveStatus("failed");
        }
      })
      .finally(() => {
        if (!cancelled) {
          setLoaded(true);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [isControlled]);

  useEffect(() => {
    if (!loaded) {
      return;
    }

    if (!hasFinishedInitialLoadRef.current) {
      hasFinishedInitialLoadRef.current = true;
      return;
    }

    if (isControlled) {
      onChange?.(normalizeAppStateSchema(state));
      return;
    }

    if (saveTimerRef.current !== null) {
      window.clearTimeout(saveTimerRef.current);
    }

    setSaveStatus("saving");
    const requestId = ++saveRequestIdRef.current;

    saveTimerRef.current = window.setTimeout(() => {
      void saveAppState(state)
        .then(() => {
          if (saveRequestIdRef.current === requestId) {
            setSaveStatus("saved");
          }
        })
        .catch(() => {
          if (saveRequestIdRef.current === requestId) {
            setSaveStatus("failed");
          }
        });
    }, 150);

    return () => {
      if (saveTimerRef.current !== null) {
        window.clearTimeout(saveTimerRef.current);
      }
    };
  }, [isControlled, loaded, onChange, state]);

  const replaceState = useCallback((nextState: AppState) => {
    setState(normalizeAppStateSchema(nextState));
  }, []);

  const actions = useMemo<AppStoreActions>(
    () => ({
      replaceState,
      createRecord: (initialValues) => {
        setState((currentState) => createRecord(currentState, initialValues));
      },
      deleteRecord: (recordId) => {
        setState((currentState) => deleteRecord(currentState, recordId));
      },
      setActiveView: (viewId) => {
        setState((currentState) =>
          currentState.database.views[viewId]
            ? {
                ...currentState,
                database: {
                  ...currentState.database,
                  activeViewId: viewId,
                  updatedAt: nowIso(),
                },
              }
            : currentState,
        );
      },
      createView: (layout = "table") => {
        setState((currentState) => {
          const nextView = {
            ...createDefaultDatabaseView(layout),
            name: getNextViewName(currentState.database.views, layout),
            layout,
          };

          return {
            ...currentState,
            database: {
              ...currentState.database,
              activeViewId: nextView.id,
              updatedAt: nowIso(),
              viewOrder: [...currentState.database.viewOrder, nextView.id],
              views: {
                ...currentState.database.views,
                [nextView.id]: nextView,
              },
            },
          };
        });
      },
      renameView: (viewId, name) => {
        setState((currentState) => updateViewInState(currentState, viewId, { name }));
      },
      moveView: (viewId, targetViewId, placement = "before") => {
        setState((currentState) => {
          const currentOrder = currentState.database.viewOrder;

          if (
            viewId === targetViewId ||
            !currentState.database.views[viewId] ||
            !currentState.database.views[targetViewId] ||
            !currentOrder.includes(viewId) ||
            !currentOrder.includes(targetViewId)
          ) {
            return currentState;
          }

          const nextOrder = currentOrder.filter(
            (currentViewId) => currentViewId !== viewId,
          );
          const targetIndex = nextOrder.indexOf(targetViewId);

          if (targetIndex === -1) {
            return currentState;
          }

          const insertionIndex =
            placement === "after" ? targetIndex + 1 : targetIndex;
          nextOrder.splice(insertionIndex, 0, viewId);

          return {
            ...currentState,
            database: {
              ...currentState.database,
              updatedAt: nowIso(),
              viewOrder: nextOrder,
            },
          };
        });
      },
      duplicateView: (viewId) => {
        setState((currentState) => {
          const sourceView = currentState.database.views[viewId];
          if (!sourceView) {
            return currentState;
          }

          const timestamp = nowIso();
          const nextView: DatabaseView = {
            ...sourceView,
            id: createDefaultDatabaseView().id,
            name: getDuplicateViewName(currentState.database.views, sourceView.name),
            sort: sourceView.sort ? { ...sourceView.sort } : null,
            filters: sourceView.filters.map((filter) => ({ ...filter })),
            tableGroupOrder: [...sourceView.tableGroupOrder],
            tableHiddenGroupIds: [...(sourceView.tableHiddenGroupIds ?? [])],
            tableCollapsedGroupIds: [...(sourceView.tableCollapsedGroupIds ?? [])],
            tableHideEmptyGroups: sourceView.tableHideEmptyGroups,
            boardColumnOrder: [...sourceView.boardColumnOrder],
            boardHiddenColumnIds: [...(sourceView.boardHiddenColumnIds ?? [])],
            boardRecordOrder: [...(sourceView.boardRecordOrder ?? [])],
            boardCardSortMode: sourceView.boardCardSortMode,
            boardShowPropertyNames: sourceView.boardShowPropertyNames,
            hiddenPropertyIds: [...sourceView.hiddenPropertyIds],
            columnWidths: { ...sourceView.columnWidths },
            createdAt: timestamp,
            updatedAt: timestamp,
          };

          return {
            ...currentState,
            database: {
              ...currentState.database,
              activeViewId: nextView.id,
              updatedAt: timestamp,
              viewOrder: [...currentState.database.viewOrder, nextView.id],
              views: {
                ...currentState.database.views,
                [nextView.id]: nextView,
              },
            },
          };
        });
      },
      deleteView: (viewId) => {
        setState((currentState) => {
          if (
            !currentState.database.views[viewId] ||
            currentState.database.viewOrder.length <= 1
          ) {
            return currentState;
          }

          const currentOrder = currentState.database.viewOrder;
          const nextOrder = currentOrder.filter((currentViewId) => currentViewId !== viewId);
          const nextViews = { ...currentState.database.views };
          delete nextViews[viewId];

          let nextActiveViewId = currentState.database.activeViewId;

          if (currentState.database.activeViewId === viewId) {
            const deletedIndex = currentOrder.indexOf(viewId);
            nextActiveViewId =
              nextOrder[Math.max(0, deletedIndex - 1)] ?? nextOrder[0];
          }

          return {
            ...currentState,
            database: {
              ...currentState.database,
              activeViewId: nextActiveViewId,
              updatedAt: nowIso(),
              viewOrder: nextOrder,
              views: nextViews,
            },
          };
        });
      },
      addProperty: (name, type, insertPosition) => {
        setState((currentState) =>
          addProperty(currentState, { name, type, insertPosition }),
        );
      },
      renameProperty: (propertyId, name) => {
        setState((currentState) => renameProperty(currentState, propertyId, name));
      },
      updatePropertyType: (propertyId, type) => {
        setState((currentState) =>
          updatePropertyType(currentState, propertyId, type),
        );
      },
      moveProperty: (propertyId, direction) => {
        setState((currentState) =>
          moveProperty(currentState, propertyId, direction),
        );
      },
      deleteProperty: (propertyId) => {
        setState((currentState) => deleteProperty(currentState, propertyId));
      },
      updateRecordValue: (recordId, property, value) => {
        setState((currentState) =>
          updateRecordValue(currentState, recordId, property, value),
        );
      },
      updatePropertyOptions: (propertyId, options) => {
        setState((currentState) =>
          updatePropertyOptions(currentState, propertyId, options),
        );
      },
      updateFormulaExpression: (propertyId, formulaExpression) => {
        setState((currentState) =>
          updateFormulaExpression(currentState, propertyId, formulaExpression),
        );
      },
      updateActiveView: (updates) => {
        setState((currentState) => {
          const currentView =
            currentState.database.views[currentState.database.activeViewId];

          if (!currentView) {
            return currentState;
          }

          const nextLayout = updates.layout ?? currentView.layout;
          const nextName =
            nextLayout !== currentView.layout
              ? getAutoRenamedViewName(
                  currentState.database.views,
                  currentView,
                  nextLayout,
                )
              : currentView.name;
          const viewUpdates: Partial<DatabaseView> = { ...updates };

          if (nextLayout !== currentView.layout && nextName !== currentView.name) {
            viewUpdates.name = nextName;
          }

          return updateViewInState(currentState, currentView.id, viewUpdates);
        });
      },
      setActiveViewSort: (sort) => {
        setState((currentState) =>
          updateViewInState(currentState, currentState.database.activeViewId, {
            sort,
          }),
        );
      },
      setActiveViewFilters: (filters) => {
        setState((currentState) =>
          updateViewInState(currentState, currentState.database.activeViewId, {
            filters,
          }),
        );
      },
      addBlock: (recordId, afterBlockId, type) => {
        const blockId = makeId("block");
        setState((currentState) =>
          addBlockAfter(currentState, recordId, afterBlockId, type, blockId),
        );
        return blockId;
      },
      updateBlockContent: (blockId, content) => {
        setState((currentState) =>
          updateBlockContent(currentState, blockId, content),
        );
      },
      patchBlock: (blockId, patch) => {
        setState((currentState) => {
          const block = currentState.blocks[blockId];
          if (!block) {
            return currentState;
          }

          return {
            ...currentState,
            blocks: {
              ...currentState.blocks,
              [blockId]: {
                ...block,
                ...patch,
                updatedAt: nowIso(),
              },
            },
          };
        });
      },
      updateBlockType: (blockId, type) => {
        setState((currentState) => updateBlockType(currentState, blockId, type));
      },
      updateBlockChecked: (blockId, checked) => {
        setState((currentState) =>
          updateBlockChecked(currentState, blockId, checked),
        );
      },
      deleteBlock: (blockId) => {
        setState((currentState) => deleteBlock(currentState, blockId));
      },
      moveBlock: (blockId, direction) => {
        setState((currentState) => moveBlock(currentState, blockId, direction));
      },
      attachImageAsset: (blockId, asset) => {
        setState((currentState) => attachImageAsset(currentState, blockId, asset));
      },
    }),
    [replaceState],
  );

  const value = useMemo(
    () => ({
      state,
      loaded,
      saveStatus: controlledSaveStatus ?? saveStatus,
      replaceState,
      actions,
    }),
    [actions, controlledSaveStatus, loaded, replaceState, saveStatus, state],
  );

  return (
    <AppStoreContext.Provider value={value}>{children}</AppStoreContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useAppStore() {
  const context = useContext(AppStoreContext);

  if (!context) {
    throw new Error("useAppStore must be used inside AppStoreProvider.");
  }

  return context;
}
